Tracer.exe : Tracer.o Parser.o ppmrw.o
	gcc Tracer.o Parser.o ppmrw.o -o Tracer.exe

Tracer.o : Tracer.c
	gcc -c Tracer.c

Parser.o : Parser.c
	gcc -c Parser.c

ppmrw.o : ppmrw.c
	gcc -c ppmrw.c
